name: build
on:
  schedule:
  - cron: "0 8 * * *"
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker image build -t mpmq:latest .

    - name: Prepare coverage
      run: |
        ID=$(docker create mpmq)
        docker cp $ID:/code/target/reports/mpmq_coverage.xml mpmq_coverage.xml
        sed -i -e 's,filename="mpmq/,filename="src/main/python/mpmq/,g' mpmq_coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: mpmq_coverage.xml
